### PR TITLE
Ah/coverage

### PR DESCRIPTION
**Pull request by HParker**
WIP

### CODE REVIEW

**Comment by XanderStrike** [comment]
I like all of this. ModelSearch is brilliant. The only thing I'd add (and you're probably planning to do this already) is that charts should be its own controller, and I was thinking about making things like top_movies, views_by_day, etc into scopes on the model but I'll leave that to your judgement.

Also, in response to your message, the format.json stuff is vestigial and if you want to remove it you have a go.

**Comment by HParker** [comment]
Great ideas! One thing I could use help on is now that we have model search stuff, I think it would be nice to make MovieSearch equally generic. I had a bit of trouble extracting all of the things that `MovieSearch#filter` does. It seems to have a lot of responsibilities. If you have any design ideas for helping join the ModelSearch code and the MovieSearch code, I think that would help alot.

**Comment by XanderStrike** [comment]
Yeah I agree. Model search could have different methods for LIKE, >, <, =, etc or something, but there's got to be a place where all the specific column names are mapped to filter actions and I don't really know where else that could be. Encode filters are also a problem because we've got to do a join in there, same with Genres (once I fix the no primary key thing :persevere:), and TV episodes (once we start storing those).

Could we keep the `MovieSearch#filter` but just use it as a wrapper for `ModelSearch`? Then when we make TV and Music search we just need to make wrappers for model search. Maybe use the include pattern you're doing with the other services and just give it one method called `movie_filter` or something.

**Comment by HParker** [comment]
@XanderStrike is this patton test failing on master? I don't think I caused it here.

**Comment by HParker** [comment]
I am calling this project complete.
screen shot 2015-03-22 at 1 55 15 am

**Comment by XanderStrike** [comment]
Hmm, the Patton test seems to depend on `MovieSearch.simple_search` which you removed as a part of this commit. You're also getting a bunch of failures where searches return no results, so I think something might be off with your search logic.

Super stoked about HomeController though. Once those tests pass we'll be in business.

**Comment by XanderStrike** [comment]
@HParker

**Pull request closed without merging**
