### PR TITLE
add immutable string literal comments

### PR DESCRIPTION
**Pull request by HParker**
Turns out caketop is already ready for immutable strings!

I ran the tests with ruby version 2.3.0 and the magic string at the top of our .rb files and everything works!

And here I was hoping I would get to fix some string mutations. :(

### CODE REVIEW

**Comment by HParker** [comment]
Funny! we actually have an encoding bug. Mind if I add a ruby version? I doubt anyone would run this with pre-2.0.0 ruby.

**Comment by XanderStrike** [comment]
What does this do?

**Comment by XanderStrike** [comment]
Also adding a ruby version is a good call. I think CircleCI was still running it on 2.0.0

**Comment by HParker** [comment]
So, it won't do anything until ruby 2.3.0 is released, but after that it will prevent you from modifying string literals.
https://bugs.ruby-lang.org/issues/11473

**Pull request closed without merging**
